In [1]:
from __future__ import print_function
import os
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR, StepLR
from data import ModelNet40
from model import PointNet, DGCNN_cls
import numpy as np
from torch.utils.data import DataLoader
from util import cal_loss, IOStream, vis_point_cloud, vis_point_cloud_side_by_side
import sklearn.metrics as metrics
import pickle
import open3d as o3d

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
class args:
    def __init__(self):
        self.batch_size = 32
        self.num_points = 1024
        self.no_cuda = not torch.cuda.is_available()
        self.cuda = torch.cuda.is_available()
        self.seed = 1
        self.exp_name = "cls_1024_eval"
        self.model = "dgcnn"
        self.dataset = "modelnet40"
        self.test_batch_size = 16
        self.epochs = 50 #original 250
        self.lr = 0.001
        self.momentum = 0.9
        self.scheduler = "cos"
        self.dropout = 0.5
        self.k = 20
        self.model_path = "pretrained/model.cls.1024.t7"
        self.emb_dims = 1024
args = args()

if not os.path.exists("outputs"):
    os.makedirs("outputs")
if not os.path.exists("outputs/" + args.exp_name):
    os.makedirs("outputs/" + args.exp_name)
if not os.path.exists("outputs/" + args.exp_name + "/" + "models"):
    os.makedirs("outputs/" + args.exp_name + "/" + "models")
os.system(
    "cp main_cls.py outputs" + "/" + args.exp_name + "/" + "main_cls.py.backup"
)
os.system("cp model.py outputs" + "/" + args.exp_name + "/" + "model.py.backup")
os.system("cp util.py outputs" + "/" + args.exp_name + "/" + "util.py.backup")
os.system("cp data.py outputs" + "/" + args.exp_name + "/" + "data.py.backup")
print(device)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
cuda


In [8]:
def test(model_path, fgsm=False, criterion=cal_loss, e=0.03):
    #sample test
    test_loader = DataLoader(
            ModelNet40(partition="test", num_points=args.num_points),
            batch_size=args.test_batch_size,
            shuffle=True,
            drop_last=False,
        )

    # Try to load models
    if args.model == "pointnet":
        model = PointNet(args).to(device)
    elif args.model == "dgcnn":
        model = DGCNN_cls(args).to(device)
    else:
        raise Exception("Not implemented")

    model = nn.DataParallel(model)
    model.load_state_dict(torch.load(model_path, map_location=torch.device("cpu")))
    model = model.to(device).eval()
    test_acc = 0.0
    count = 0.0
    test_true = []
    test_pred = []
    for data, label in test_loader:
        count += 1
        # print(count / len(test_loader))
        data, label = data.to(device), label.to(device).squeeze()
        data = data.permute(0, 2, 1)
        preds = None
        if fgsm:
            data.requires_grad = True
            model.zero_grad()
            logits = model(data)
            loss = criterion(logits, label) #get grad data
            loss.backward()
            
            #perform fgsm
            data_grad = data.grad.data
            perturbed = data + e * data_grad.sign()
            perturbed_logits = model(perturbed)
            preds = perturbed_logits.max(dim=1)[1]
        else:
            batch_size = data.size()[0]
            logits = model(data)
            preds = logits.max(dim=1)[1]
        test_true.append(label.cpu().numpy())
        test_pred.append(preds.detach().cpu().numpy())
    test_true = np.concatenate(test_true)
    test_pred = np.concatenate(test_pred)
    test_acc = metrics.accuracy_score(test_true, test_pred)
    avg_per_class_acc = metrics.balanced_accuracy_score(test_true, test_pred)
    outstr = "Test :: test acc: %.6f, test avg acc: %.6f" % (
        test_acc,
        avg_per_class_acc,
    )
    print(outstr)

model_path = "./izzymodels/02.pth"
test(model_path,fgsm=True)
test("./pretrained/model.cls.1024.t7",fgsm=True)

Test :: test acc: 0.847245, test avg acc: 0.778064
Test :: test acc: 0.728930, test avg acc: 0.648407


In [21]:
#train
train_loader = DataLoader(
        ModelNet40(partition="train", num_points=args.num_points),
        num_workers=8,
        batch_size=args.batch_size,
        shuffle=False,
        drop_last=True,
    )
test_loader = DataLoader(
    ModelNet40(partition="test", num_points=args.num_points),
    num_workers=8,
    batch_size=args.test_batch_size,
    shuffle=True,
    drop_last=False,
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Try to load models
if args.model == "pointnet":
    model = PointNet(args).to(device)
elif args.model == "dgcnn":
    model = DGCNN_cls(args).to(device)
else:
    raise Exception("Not implemented")

# print(str(model))

model = nn.DataParallel(model)
print("Let's use", torch.cuda.device_count(), "GPUs!")

opt = optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-4)

if args.scheduler == "cos":
    scheduler = CosineAnnealingLR(opt, args.epochs, eta_min=1e-3)
elif args.scheduler == "step":
    scheduler = StepLR(opt, step_size=20, gamma=0.7)

criterion = cal_loss
best_test_acc = 0

EPSILON = 0.2
epsilons = [0.02, 0.05] #omitted 0.1
accuracies = {}

for e in epsilons:
    print("Epsilon: ", e)
    model = DGCNN_cls(args).to(device)
    model = nn.DataParallel(model)
    opt = optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-4)
    if args.scheduler == "cos":
        scheduler = CosineAnnealingLR(opt, args.epochs, eta_min=1e-3)
    elif args.scheduler == "step":
        scheduler = StepLR(opt, step_size=20, gamma=0.7)

    for epoch in range(args.epochs):
        ####################
        # Train
        ####################
        train_loss = 0.0
        count = 0.0
        model.train()
        train_pred = []
        train_true = []
        for data, label in train_loader:
            data, label = data.to(device), label.to(device).squeeze()
            data = data.permute(0, 2, 1)
            data.requires_grad = True
            batch_size = data.size()[0]
            opt.zero_grad()
            logits = model(data)
            loss = criterion(logits, label)
            loss.backward()
            opt.step()
            train_loss += loss.item() * batch_size
            vis_data = data.permute(0, 2, 1).cpu().detach().numpy()

            #perform fgsm
            # normalized_grad = F.normalize(data.grad.data, p=2, dim=1) #dim 1 because the shape is 64 x 3 x 1024
            # mask = normalized_grad > e
            # normalized_grad[mask] *= e
            # perturbed = data - normalized_grad
            # perturbed = torch.clamp(perturbed, 0, 1)

            # remove salient points
            gradients = data.grad.data.norm(2, dim=1) #dim=batchx1024 points
            saliency_map = gradients.squeeze().detach().cpu().numpy()
            print("saliency map ",saliency_map)
            # print(saliency_map)

            # vis_data_perturbed = perturbed.permute(0, 2, 1).cpu().detach().numpy()
            # vis_point_cloud_side_by_side(vis_data[0], vis_data_perturbed[0])
            
            #training model with fgsm data
            opt.zero_grad()
            perturbed_logits = model(perturbed)
            loss = criterion(perturbed_logits, label)
            loss.backward()
            opt.step()
            train_loss += loss.item() * batch_size

            #calculate accuracy
            preds = logits.max(dim=1)[1]
            preds_perturbed = perturbed_logits.max(dim=1)[1]
            count += batch_size * 2
            train_true.append(label.cpu().numpy())
            train_true.append(label.cpu().numpy())
            train_pred.append(preds.detach().cpu().numpy())
            train_pred.append(preds_perturbed.detach().cpu().numpy())
            
        if args.scheduler == "cos":
            scheduler.step()
        elif args.scheduler == "step":
            if opt.param_groups[0]["lr"] > 1e-5:
                scheduler.step()
            if opt.param_groups[0]["lr"] < 1e-5:
                for param_group in opt.param_groups:
                    param_group["lr"] = 1e-5
        train_true = np.concatenate(train_true)
        train_pred = np.concatenate(train_pred)
        outstr = "\tEpoch %d, loss: %.6f, train acc: %.6f, train avg acc: %.6f" % (
            epoch,
            train_loss * 1.0 / count,
            metrics.accuracy_score(train_true, train_pred),
            metrics.balanced_accuracy_score(train_true, train_pred),
        )
        print(outstr)
        accuracies[e] = metrics.accuracy_score(train_true, train_pred)
    # path = "./izzymodels/"+str(e)[2:] + ".pth"
    # torch.save(model.state_dict(), path)
accuracies

Let's use 2 GPUs!
Epsilon:  0.02
saliency map  [[0.02375056 0.01455437 0.01728053 ... 0.01559228 0.00964051 0.01912671]
 [0.02239146 0.02229409 0.01471183 ... 0.01833074 0.03425038 0.00452327]
 [0.01405055 0.00711348 0.01666957 ... 0.00816903 0.00657282 0.0029636 ]
 ...
 [0.04536456 0.03364614 0.01294399 ... 0.00907554 0.01119856 0.02130798]
 [0.07092025 0.00800915 0.00254139 ... 0.02931549 0.00464037 0.00655981]
 [0.03729999 0.00797501 0.02748266 ... 0.05443222 0.01851181 0.03828617]]
saliency map  [[0.02450571 0.00558111 0.0170668  ... 0.00440767 0.02532902 0.01765362]
 [0.01064083 0.00995886 0.00612512 ... 0.01576745 0.00653083 0.00657822]
 [0.00688514 0.00726292 0.01230462 ... 0.00412801 0.00676066 0.01025804]
 ...
 [0.00503974 0.03163066 0.01412452 ... 0.03110735 0.02116289 0.00618947]
 [0.00573082 0.00583773 0.00234504 ... 0.00313634 0.00963182 0.00217987]
 [0.01129454 0.00815741 0.00875588 ... 0.01122945 0.00641239 0.00452413]]
saliency map  [[0.00434654 0.00926944 0.01723712 ..

KeyboardInterrupt: 

In [7]:
# Assuming you have a tensor
tensor = torch.tensor([1.5, 2.7, 0.8, 3.2, 1.1])

threshold = 2.0
multiplication_factor = 2

# Create a mask for elements above the threshold
mask = tensor > threshold

# Multiply elements above the threshold by the multiplication factor
result = tensor.clone()  # Create a copy of the original tensor
result[mask] *= multiplication_factor

print(result)


tensor([1.5000, 5.4000, 0.8000, 6.4000, 1.1000])


In [7]:
mod = DGCNN_cls(args).to(device)
mod = nn.DataParallel(mod)
mod.load_state_dict(torch.load(args.model_path, map_location=torch.device(device)))

train_loader = DataLoader(
        ModelNet40(partition="train", num_points=args.num_points),
        num_workers=8,
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=True,
    )
print("getting sample")
sample = None
label = None
for data, l in train_loader:
    print(0)
    data, l = data.to(device), l.to(device).squeeze()
    sample, label = data, l
    break
vis_point_cloud(sample[0].cpu())

getting sample
0


In [5]:
accuracies

{0.02: 0.8888436482084691, 0.05: 0.7661339576547231}

In [3]:
model_path = "./izzymodels/02.pth"
test(model_path,fgsm=True)

0.0064516129032258064


AttributeError: 'NoneType' object has no attribute 'data'